### ISSUE TITLE
关于代码中的所需文件

### ISSUE THREAD

**Issue by hyleepp** [DexterZeng/UEA#1]
老师您好：

在复现代码的过程中，我发现其中缺少main中需要读取的_vectorList.json和string_mat.npy文件。请问是需要先运行另外一个脚本来生成这两个文件吗，还是现在的数据集中本身缺少了这一部分呢？

谢谢老师！

**Comment by DexterZeng** [comment]
十分抱歉没有及时看到问题。关于_vectorList.json，这个是名字的词向量，我们直接采用 (https://github.com/StephanieWyt/RDGCN) 这个工作中的，如果无法下载到可以用这个链接 （https://share.weiyun.com/5qxLmEI） 。
string_mat.npy这个就是用levenshiten函数生成string-level的距离，已经补上了相关函数文件。

感谢对我们工作的关注，还有疑问可以直接发邮件到zengweixin13@nudt.edu.cn，会及时回复。
